/*
This file was generated by the following command:

/home/ben/software/install/bin/cfunctions unicode-character-class.c

*/
#ifndef CFH_UNICODE_CHARACTER_CLASS_H
#define CFH_UNICODE_CHARACTER_CLASS_H

#line 10 "unicode-character-class.c"
int32_t ucs2_is_kana (int32_t ucs);

#line 20 "unicode-character-class.c"
int32_t utf8_is_kana_chars (const uint8_t* utf8, int32_t len);

#line 41 "unicode-character-class.c"
int32_t utf16_is_kanji (int32_t utf16);

#endif /* CFH_UNICODE_CHARACTER_CLASS_H */
