/*
This file was generated by the following command:

/home/ben/software/install/bin/cfunctions unicode-character-class.c

*/
#ifndef CFH_UNICODE_CHARACTER_CLASS_H
#define CFH_UNICODE_CHARACTER_CLASS_H

#line 10 "unicode-character-class.c"
int ucs2_is_kana (int ucs);

#line 20 "unicode-character-class.c"
int utf8_is_kana_chars (const unsigned char* utf8, int len);

#line 41 "unicode-character-class.c"
int utf16_is_kanji (int utf16);

#endif /* CFH_UNICODE_CHARACTER_CLASS_H */
